# Generated by Django 2.2.13 on 2021-03-19 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_order_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='ammount',
            field=models.FloatField(default=20),
            preserve_default=False,
        ),
    ]
