# Generated by Django 2.2.13 on 2021-03-19 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_coupon_ammount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='ammount',
            new_name='amount',
        ),
    ]
