# Generated by Django 2.2.13 on 2021-03-19 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20210319_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ref_code',
            field=models.CharField(default='JDE123', max_length=10),
            preserve_default=False,
        ),
    ]
